[package]
name = "oppg1"
version = "0.1.0"
authors = ["Sveinung Ã˜verland <39273837+SveinungOverland@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
